name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64
          cache: 'maven'

      - name: Building application JAR
        run: mvn clean package

      - name: Launch the application
        run: nohup java -jar target/formation-cicd-test-tp-03-1.0-SNAPSHOT.jar > ../app.log 2>&1 &

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/health > /dev/null; then
              echo "API is up!"
              exit 0
            fi
            echo "Waiting API..."
            sleep 2
          done
          echo "API not ready"
          tail -n 200 app.log || true
          exit 1

      - name: Prepare API tests reports directory
        run: mkdir -p api-test-reports

      - name: Run API tests (Hurl via Docker)
        run: |
          docker run --rm \
            --add-host=host.docker.internal:host-gateway \
            -v ${{ github.workspace }}:/work \
            ghcr.io/orange-opensource/hurl:latest \
            --test \
            --report-junit /work/api-test-reports/junit.xml \
            --report-html /work/api-test-reports/report.html \
            --report-json /work/api-test-reports/report.json \
          /work/src/test/java/api

      - name: Stop the application
        if: always()
        run: |
          APP_PID=$(lsof -t -i:8080)
              if [ -n "$APP_PID" ]; then
                kill $APP_PID
                echo "Application stopped."
              else
                echo "No application running on port 8080."
              fi

      - name: Uploading report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: api-test-reports

  security-tests:
    needs: api-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64
          cache: 'maven'

      - name: Building application JAR
        run: mvn clean package

      - name: Launch the application
        run: nohup java -jar target/formation-cicd-test-tp-03-1.0-SNAPSHOT.jar > ../app.log 2>&1 &

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/health > /dev/null; then
              echo "API is up!"
              exit 0
            fi
            echo "Waiting API..."
            sleep 2
          done
          echo "API not ready"
          tail -n 200 app.log || true
          exit 1

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
            target: 'http://localhost:8080/'
            artifact_name: 'zap_scan'
            fail_action: false

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: report_*.*

      - name: Stop the application
        if: always()
        run: |
          APP_PID=$(lsof -t -i:8080)
              if [ -n "$APP_PID" ]; then
                kill $APP_PID
                echo "Application stopped."
              else
                echo "No application running on port 8080."
              fi
